/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto_final_cj;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author hugob
 */
public class PanelIngresar extends javax.swing.JPanel {

    PanelPagar panelPago = new PanelPagar();
    /**
     * Creates new form IngresarVehiculo
     */
    public PanelIngresar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresar = new javax.swing.JButton();
        txtMatriculaIngresar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnIngresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngresar.setText("Registrar Entrada");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        txtMatriculaIngresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMatriculaIngresar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMatriculaIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaIngresarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Introduce la matrícula de tu vehículo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Sistema de gestión de aparcamiento Aparka-t, SLU  ");

        jLabel3.setText("Tarifa Vigente:");

        jLabel4.setText("Precio por minuto");

        jLabel5.setText(Double.toString(panelPago.getTARIFA_MINUTOS()));

        jLabel6.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnIngresar)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtMatriculaIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(txtMatriculaIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnIngresar)
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       try{
           //Creamos la conexión con la base de datos
           Class.forName("com.mysql.jdbc.Driver"); 
           Connection cnx = DriverManager.getConnection("jdbc:mysql://localhost/bdparking","root","");
           Statement sentencia=cnx.createStatement();
           
           //Damos formato a la fecha e instanciamos los objetos necesarios para obtenerla
           DateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd HH:mm:ss");
           Calendar cal = Calendar.getInstance();
           Date date = cal.getTime();
           String fechaHora = dateFormat.format(date);
           
           //Creamos un string con la matrícula introducida y los patrones para verificar que sea un formato correcto
           String matricula = txtMatriculaIngresar.getText().toUpperCase().trim();
           String patronAntiguo = "^[A-Z]{1,2}[0-9]{4}[BCDFGHJKLMNPRSTVWXYZ]{2}";//Este es el formato antiguo de las matrículas españolas
           String patronNuevo = "^[0-9]{4}[BCDFGHJKLMNPRSTVWXYZ]{3}";//Este es el formato actual de la matrícula española 
           
           //Verificamos que la matrícula cumpla los patrones indicados
           if(matricula.matches(patronAntiguo) || matricula.matches(patronNuevo)){
               
               //Lanzamos una consulta la base de datos para verificar que el vehículo no está dentro del parking
               ResultSet rs = sentencia.executeQuery("SELECT * FROM vehiculos WHERE matricula='"+matricula+"' AND estaDentro=true");
               //Si el vehículo se encuentra dentro de las instalaciones, lo indicamos con un mensaje al usuario
               if(rs.next()){
                    JOptionPane.showMessageDialog(this, "El vehículo ya se ha registrado y se encuentra dentro del parking"+System.lineSeparator()+
                                "Hora de entrada: "+rs.getString("horaEntrada"), "Vehículo ya registrado", JOptionPane.INFORMATION_MESSAGE);
               }
               //Si el vehículo no está dentro del parking, procedemos a registrarlo
               else {
                String sql = "INSERT INTO vehiculos (matricula, horaEntrada) VALUES ('"+matricula+"','"+fechaHora+"')";
                System.out.println(sql);
                boolean insertado = sentencia.execute(sql);
                JOptionPane.showMessageDialog(this, "Vehículo dentro del parking"+System.lineSeparator()+"Hora de entrada: "+ fechaHora+System.lineSeparator()+"Matrícula: "+ matricula, "Mensaje de confirmación", JOptionPane.INFORMATION_MESSAGE);
                this.txtMatriculaIngresar.setText("");
               }
           }
           
           //Si la matrícula no cumple los requisitos de formato, mostramos un mensaje de error
           else{
              JOptionPane.showMessageDialog(this,"Debe introducir una matrícula válida sin espacios ni guiones\n Ejemplo: 1234BCD o C2779BH","Alerta - Formato no valido", JOptionPane.ERROR_MESSAGE);
              this.txtMatriculaIngresar.setText("");
           }
           //Se cierra la conexión con la BD
           cnx.close();
       }
       catch(HeadlessException | ClassNotFoundException | SQLException e){
           System.out.println("ERROR "+e.getLocalizedMessage());
       }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtMatriculaIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtMatriculaIngresar;
    // End of variables declaration//GEN-END:variables
}
